### ISSUE TITLE
Collapse nodes with the same name (doesnt matter to which one)

### ISSUE THREAD

**Issue by ddomingof** [pybel/pybel-tools#137]
@jmarinllao

Relabel nodes with the same name and combine them

**Comment by cthoyt** [comment]
Shouldn't be so bad except for nodes appearing in complexes, composites, fusions, and reactants will be tricky

**Comment by cthoyt** [comment]
@jmarinllao It's a crude first step, but give https://github.com/pybel/pybel-tools/commit/815a98afd45dd58e20e5a0060a1b6a972a1ad31a a try.

If/when it doesn't work, you can re-open this issue, write more unit tests corresponding to the situations, and I can update the implementation.
