### ISSUE TITLE
Generate human-readable documentation for Javascript

### ISSUE THREAD

**Issue by cthoyt** [pybel/pybel-tools#79]
It's come to my attention that I'm not aware of the community format used for documenting Javascript code. It would be nice to know:

1. What's the community standard for javascript documentation (like how Sphinx/Google/Napoleon are format(s) for Python)
2. What software can read javascript files and generate pretty documentation (like how Sphinx does for python
3. What community services exist for hosting javascript documentation (like how ReadTheDocs does for python)
4. How do we make Travis-CI do this all for us

A bit of time investment here will help us go a long way in the future :)

**Comment by ddomingof** [comment]
i fully agree. see my last commit

i am following jsdocs. it seems it is the most used one but i will look more tomorrow.

**Comment by cthoyt** [comment]
^ that's what made me think of this! Google sent me here: http://usejsdoc.org/. Let me know if you find a tool on that site for building the documentation to HTML or something like that

**Comment by ddomingof** [comment]
Yep! That's what I followed. I will finish tomorrow with that and search for the documentation builder.

**Comment by ddomingof** [comment]
By the way really nice video about readability what you shared in that commit. A oneliner is not always the best after all...

**Comment by cthoyt** [comment]
Agreed. I'm going to go and fix all of my awful one-liners to look more beautiful like how he described.

**Comment by ddomingof** [comment]
hahaha sorry for that :(
they are not awful though

**Comment by ddomingof** [comment]
After installing jsdoc3 https://github.com/jsdoc3/jsdoc
running jsdoc --file will create the html file....

**Comment by cthoyt** [comment]
Can you add an explanation of this into the docs?
