### ISSUE TITLE
Multiple Edges Visualization

### ISSUE THREAD

**Issue by cthoyt** [pybel/pybel-tools#90]
Lets do a hackathon this week and get this working. Examples/resources:

- http://bl.ocks.org/aureooms/7daf089f0936b9e16aa9
- http://bl.ocks.org/GerHobbelt/3616279
- https://stackoverflow.com/questions/13771956/can-d3-force-layout-visualize-multigraph
- https://stackoverflow.com/questions/11368339/drawing-multiple-edges-between-two-nodes-with-d3

**Comment by ddomingof** [comment]
This is something we already discussed. I wouldnt implement this as a primary visualization. Maybe as a secondary since with the multiple edges PyBEl creates it will look bad...
